steps:
  - name: maven:3-eclipse-temurin-17-alpine
    entrypoint: mvn
    args: ["test"]
  - name: maven:3-eclipse-temurin-17-alpine
    entrypoint: mvn
    args: ["package", "-Dmaven.test.skip=true"]
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "us-central1-docker.pkg.dev/stoked-mode-410819/samplespringbootrepo/samplespringboot", "--build-arg=JAR_FILE=target/app.jar", "."]
images: ["us-central1-docker.pkg.dev/stoked-mode-410819/samplespringbootrepo/samplespringboot"]

